import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";

// React and Lucide are build inputs only. The ZIP has a self-contained ESM entry.
const require = createRequire(new URL("../../../apps/desktop/package.json", import.meta.url));
const React = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const lucide = require("lucide-react");
const source = await readFile(new URL("src/review-source.html", import.meta.url), "utf8");
const parts = source.match(/^<style>([\s\S]*?)<\/style>\s*([\s\S]*?)<script>([\s\S]*?)<\/script>\s*$/);
if (!parts) throw new Error("试用源文件需要一个 style、根节点和 script");
const [, css, markup, controller] = parts;
const icons = {};
for (const [, name] of source.matchAll(/data-lucide="([a-z-]+)"/g)) {
  if (icons[name]) continue;
  const key = name.split("-").map((s) => s[0].toUpperCase() + s.slice(1)).join("");
  if (!lucide[key]) throw new Error(`缺少本地图标：${name}`);
  icons[name] = renderToStaticMarkup(React.createElement(lucide[key], { "aria-hidden": true, focusable: false }));
}
const runtime = await readFile(new URL("src/runtime.js", import.meta.url), "utf8");
const output = `// Generated by build.mjs. Edit src/ and rebuild. Demo UI only.\n` +
  `const CSS = ${JSON.stringify(css)};\nconst MARKUP = ${JSON.stringify(markup)};\nconst ICONS = ${JSON.stringify(icons)};\n` +
  `function createTrialController() {\n` +
  `  const template = document.createElement("template");\n  template.innerHTML = MARKUP;\n` +
  `  const root = template.content.firstElementChild;\n` +
  `  const style = document.createElement("style");\n  style.dataset.jobTrackerTrial = "";\n  style.textContent = CSS;\n` +
  `  const listeners = new AbortController();\n` +
  `  const listen = (target, type, handler, options = {}) => target.addEventListener(type, handler, { ...options, signal: listeners.signal });\n` +
  `  try {\n    document.head.append(style);\n${controller}\n  } catch (error) { listeners.abort(); style.remove(); root.remove(); throw error; }\n}\n` + runtime;
await writeFile(new URL("main.js", import.meta.url), output);
console.log(`main.js: ${Buffer.byteLength(output)} bytes, ${Object.keys(icons).length} local SVG icons`);
